apiVersion: v2
name: my-app
description: Un Chart de Helm para desplegar una aplicación completa con frontend, backend y base de datos
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: frontend
    version: "0.1.0"
    repository: "file://charts/frontend"
  - name: backend
    version: "0.1.0"
    repository: "file://charts/backend"
  - name: database
    version: "0.1.0"
    repository: "file://charts/database"
