apiVersion: v1
kind: Service
metadata:
  name: backend  # Nombre del servicio
spec:
  type: {{ .Values.service.type }}  # Tipo de servicio (por ejemplo, ClusterIP, NodePort)
  ports:
    - port: {{ .Values.service.port }}  # Puerto en el que el servicio estará disponible
  selector:
    app: backend  # Selector que coincide con la etiqueta 'app' de los pods para dirigir el tráfico
