apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "database.fullname" . }}-pvc  # Nombre del PersistentVolumeClaim, usando el nombre completo definido en los helpers
  labels:
    app: {{ include "database.name" . }}         # Etiqueta 'app' con el nombre de la aplicación, definido en los helpers
spec:
  accessModes:
    {{ toYaml .Values.persistentVolumeClaim.accessModes | indent 4 }}  # Modos de acceso al volumen, obtenidos de values.yaml y formateados correctamente
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.resources.requests.storage }}  # Tamaño de almacenamiento solicitado, obtenido de values.yaml
