apiVersion: v1  # Versión de la API de Kubernetes utilizada
kind: Service  # Tipo de recurso: Service (expone una aplicación como un servicio de red)
metadata:
  name: frontend  # Nombre del servicio, se utilizará para acceder al servicio dentro del clúster
spec:
  type: {{ .Values.service.type }}  # Tipo de servicio (por ejemplo, ClusterIP, NodePort), obtenido de values.yaml
  ports:
    - port: {{ .Values.service.port }}  # Puerto en el que el servicio estará disponible, definido en values.yaml
  selector:
    app: frontend  # Selector que coincide con la etiqueta 'app' de los pods para dirigir el tráfico al frontend
